headersOrigin = "inline"
redirectsOrigin = "inline"

[functions]

[functions."*"]

[[plugins]]
origin = "config"
package = "@netlify/plugin-nextjs"

[plugins.inputs]

[build]
publish = "/Users/jonathonc/Auto1111/claude/marketing-agent-v2/agentic-marketing-generator/.next"
publishOrigin = "config"
commandOrigin = "config"
command = "pnpm install && pnpm run build"

[build.environment]
NEXT_TELEMETRY_DISABLED = "1"
PNPM_FLAGS = "--shamefully-hoist"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "*.yml"

[headers.values]
Content-Type = "text/yaml"
Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
for = "/admin/config.yml"

[headers.values]
Content-Type = "text/yaml"
Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
for = "/blog/*"

[headers.values]
Cache-Control = "public, max-age=3600, s-maxage=86400, stale-while-revalidate=604800"

[[headers]]
for = "/*.css"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*.js"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/images/*"

[headers.values]
Cache-Control = "public, max-age=604800, s-maxage=2592000"

[[headers]]
for = "/*"

[headers.values]
X-Powered-By = ""
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
Permissions-Policy = "camera=(), microphone=(), geolocation=(), accelerometer=(), gyroscope=(), magnetometer=(), payment=(), usb=()"
Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://identity.netlify.com https://unpkg.com https://res.cloudinary.com https://widget.cloudinary.com https://upload-widget.cloudinary.com https://app.tina.io https://*.tinajs.io; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: blob: https://res.cloudinary.com https://images.unsplash.com https://cloudinary.com https://app.tina.io https://*.tinajs.io; media-src 'self' https://res.cloudinary.com; connect-src 'self' https://api.cloudinary.com https://res.cloudinary.com https://identity.netlify.com wss://identity.netlify.com https://*.netlify.com https://*.netlify.app https://app.tina.io https://*.tinajs.io wss://*.tinajs.io; frame-src 'self' https://identity.netlify.com https://widget.cloudinary.com https://upload-widget.cloudinary.com https://app.tina.io; object-src 'none'; base-uri 'self'; form-action 'self' https://identity.netlify.com; frame-ancestors 'none'; upgrade-insecure-requests"
X-DNS-Prefetch-Control = "on"
Link = "<https://fonts.googleapis.com>; rel=preconnect, <https://fonts.gstatic.com>; rel=preconnect, <https://res.cloudinary.com>; rel=preconnect"

[[headers]]
for = "/admin"

[headers.values]
Cache-Control = "public, max-age=0, must-revalidate"
Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://identity.netlify.com https://unpkg.com https://res.cloudinary.com https://widget.cloudinary.com https://upload-widget.cloudinary.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: blob: https://res.cloudinary.com https://images.unsplash.com https://cloudinary.com https://api.netlify.com; media-src 'self' https://res.cloudinary.com; connect-src 'self' https://api.cloudinary.com https://res.cloudinary.com https://identity.netlify.com wss://identity.netlify.com https://*.netlify.com https://*.netlify.app https://api.netlify.com; frame-src 'self' https://identity.netlify.com https://widget.cloudinary.com https://upload-widget.cloudinary.com; object-src 'none'; base-uri 'self'; form-action 'self' https://identity.netlify.com; frame-ancestors 'none'; upgrade-insecure-requests"

[[headers]]
for = "/admin/index.html"

[headers.values]
Cache-Control = "public, max-age=0, must-revalidate"
Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://identity.netlify.com https://unpkg.com https://res.cloudinary.com https://widget.cloudinary.com https://upload-widget.cloudinary.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: blob: https://res.cloudinary.com https://images.unsplash.com https://cloudinary.com https://api.netlify.com; media-src 'self' https://res.cloudinary.com; connect-src 'self' https://api.cloudinary.com https://res.cloudinary.com https://identity.netlify.com wss://identity.netlify.com https://*.netlify.com https://*.netlify.app https://api.netlify.com; frame-src 'self' https://identity.netlify.com https://widget.cloudinary.com https://upload-widget.cloudinary.com; object-src 'none'; base-uri 'self'; form-action 'self' https://identity.netlify.com; frame-ancestors 'none'; upgrade-insecure-requests"

[[headers]]
for = "/admin/*"

[headers.values]
Cache-Control = "public, max-age=0, must-revalidate"
Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://identity.netlify.com https://unpkg.com https://res.cloudinary.com https://widget.cloudinary.com https://upload-widget.cloudinary.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: blob: https://res.cloudinary.com https://images.unsplash.com https://cloudinary.com https://api.netlify.com; media-src 'self' https://res.cloudinary.com; connect-src 'self' https://api.cloudinary.com https://res.cloudinary.com https://identity.netlify.com wss://identity.netlify.com https://*.netlify.com https://*.netlify.app https://api.netlify.com; frame-src 'self' https://identity.netlify.com https://widget.cloudinary.com https://upload-widget.cloudinary.com; object-src 'none'; base-uri 'self'; form-action 'self' https://identity.netlify.com; frame-ancestors 'none'; upgrade-insecure-requests"

[[headers]]
for = "/_next/static/*"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
from = "/_next/image/"
to = "/.netlify/images?url=:url&w=:width&q=:quality"
status = 200.0
force = false

[redirects.query]
url = ":url"
w = ":width"
q = ":quality"

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/_ipx/*"
to = "/.netlify/images?url=:url&w=:width&q=:quality"
status = 200.0
force = false

[redirects.query]
url = ":url"
w = ":width"
q = ":quality"

[redirects.conditions]

[redirects.headers]